credentials:
  usernames:
    ahmed:
      email: "ahmssmourad@gmail.com"
      name: "Ahmed"
      password: "$2b$12$QoUvJRebh4efN9lZ2b5eNOSbWMX7JcCwcu6aTSxP0pINyxpOuHv56"   # hashed later
cookie:
  expiry_days: 1
  name: "auth_cookie"
  key: "something_random"