[auth]
cookie_name = "finmgr"
cookie_key = "knigtsKind"
cookie_expiry_days = 7

[auth.credentials]
usernames = ["ahmed"]
names = ["Ahmed Mourad"]
hashed_passwords = ["$2b$12$QoUvJRebh4efN9lZ2b5eNOSbWMX7JcCwcu6aTSxP0pINyxpOuHv56"]